### ISSUE TITLE
Does this work with the Camera Link protocol

### ISSUE THREAD

**Issue by ZmjbS** [rustyoz/cameralink#1]
Hi,

I'm trying to get a thermal image camera to work with OpenCV. The camera has a [Camera Link](https://en.wikipedia.org/wiki/Camera_Link) interface but I'm struggling to access it. This will all be running on Linux so before diving in to read your code and consider porting it to Linux, I'm wondering if this is even what I'm looking for.

So, is this for use with the Camera Link standard, or do they just share the name?

Cheers,
Martin

**Comment by rustyoz** [comment]
No it doesn't implement this interface. Just an unfortunate name collision
